# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: 杨阳
 params:
   description: 研究助理教授
 menu:
   main:
     - name: 关于
       url: '#about'
       weight: 1

     - name: 研究
       url: '#featured'
       weight: 2

     - name: 招聘监测
       url: '#job-tracker'
       weight: 3

     - name: 会议
       url: '#talks'
       weight: 4

     - name: 联系
       url: '#contact'
       weight: 5
